FROM golang:1.23.2-alpine
WORKDIR /go/src/app
COPY app/main.go app/go.mod app/go.sum ./
RUN go mod download
RUN go install golang.org/x/tools/cmd/goimports@latest
RUN go install honnef.co/go/tools/cmd/staticcheck@latest
RUN go install github.com/air-verse/air@v1.61.1
CMD ["air", "-c", ".air.toml"]
